### ISSUE TITLE
Strange behavior of kor-menu-item active property

### ISSUE THREAD

**Issue by gcollin** [eduferfer/kor#6]
Hello,
I have 2 menus in a pane, each displaying a specific page (using Angular Router), and I would like the menu of the current page to be in active state.
So I did something like this:
```
<kor-menu-item (click)="gotoPage('/')" [active]="isActive('/')" label="Home" toggle="false" icon="home"></kor-menu-item>
<kor-menu-item (click)="gotoPage('dev')" [active]="isActive('dev')" label="Dev" toggle="false" icon="memory"></kor-menu-item>
```

with the following methods:
```
 gotoPage(page:string): void {
    this.router.navigate([page]);
  }

  isActive(page:string):boolean {
    const ret = this.router.isActive(page, true);
    console.log(page +' is active:'+ret);
    return ret;
  }

```

The issue:
Despite seeing
```
/ is active:true
dev is active:false

```
in the console, the first menu-item (for '/') is not displayed as active. Both menus are inactive....

Is there any error here ?

**Comment by eduferfer** [comment]
Hey @gcollin , I tried out the scenario you described and found out that it is happening because toggle is still set to true (in HTML5 any value assigned in line will return true, e.g. `toggle="false"` is the same as `toggle=""`).

Any of the following solutions would resolve you problem:
- Bind toggle to an actual false property. Example:
```html
[toggle]="myFalseBool"
```
- Stop the propagation of the click event to prevent the toggle behavior. Example:
```html
click)="$event.stopImmediatePropagation(); gotoPage('/')"
```

**Comment by gcollin** [comment]
Oh yes, my bad. I forgot to put toggle under squared bracket:

`<kor-menu-item (click)="gotoPage('/')" [active]="isActive('/')" label="Home" [toggle]="false" icon="home"></kor-menu-item>`

And now it's working fine ! Thanks for the help.
